kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: openshift-backend-from-pipeline
  namespace: jpcaetano-dev
spec:
  scaleTargetRef:
    kind: Deployment
    name: openshift-backend
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80